<a href="https://colab.research.google.com/github/Kisara10/Match-prediction--ML-/blob/prediction-code/Match_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import libarires
import pandas as pd
import numpy as np

In [ ]:
# Get the file and display first five rows
df = pd.read_csv("/content/ODI_cricinfo.csv")
df.head()

,Scorecard,Team 1,Team 2,Winner,Margin,Ground,Match Date
0,ODI # 1,Australia,England,Australia,5 wickets,Melbourne,"Jan 5, 1971"
1,ODI # 2,England,Australia,England,6 wickets,Manchester,"Aug 24, 1972"
2,ODI # 3,England,Australia,Australia,5 wickets,Lord's,"Aug 26, 1972"
3,ODI # 4,England,Australia,England,2 wickets,Birmingham,"Aug 28, 1972"
4,ODI # 5,New Zealand,Pakistan,New Zealand,22 runs,Christchurch,"Feb 11, 1973"

In [ ]:
# Check the data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4124 entries, 0 to 4123
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Scorecard   4124 non-null   object
 1   Team 1      4124 non-null   object
 2   Team 2      4124 non-null   object
 3   Winner      4124 non-null   object
 4   Margin      3938 non-null   object
 5   Ground      4124 non-null   object
 6   Match Date  4124 non-null   object
dtypes: object(7)
memory usage: 225.7+ KB

In [ ]:
df.describe()

,Scorecard,Team 1,Team 2,Winner,Margin,Ground,Match Date
count,4124,4124,4124,4124,3938,4124,4124
unique,4124,25,26,26,235,176,3540
top,ODI # 4124,Australia,Pakistan,Australia,6 wickets,Sharjah,"Feb 4, 2007"
freq,1,599,530,566,360,238,6

In [ ]:
# Number of rows and columns
df.shape

(4124, 7)

In [ ]:
# Check missing data values
df.isnull().sum()

Scorecard       0
Team 1          0
Team 2          0
Winner          0
Margin        186
Ground          0
Match Date      0
dtype: int64

In [ ]:
# Remove the "Margin" column
df.drop(['Margin', 'Scorecard'], axis=1, inplace=True)
df.head()

        Team 1     Team 2       Winner        Ground    Match Date
0    Australia    England    Australia     Melbourne   Jan 5, 1971
1      England  Australia      England    Manchester  Aug 24, 1972
2      England  Australia    Australia        Lord's  Aug 26, 1972
3      England  Australia      England    Birmingham  Aug 28, 1972
4  New Zealand   Pakistan  New Zealand  Christchurch  Feb 11, 1973

In [ ]:
# Select the features and targets
x = df[['Team 1', 'Team 2', 'Ground']]
y = df['Winner']

In [ ]:
# Convert the labels into numbers
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Team 1'] = le.fit_transform(df['Team 1'])
df['Team 2'] = le.fit_transform(df['Team 2'])
df['Ground'] = le.fit_transform(df['Ground'])
df['Winner'] = le.fit_transform(df['Winner'])

df.head()

   Team 1  Team 2  Winner  Ground    Match Date
0       3       7       3     103   Jan 5, 1971
1       8       2       7     101  Aug 24, 1972
2       8       2       3      98  Aug 26, 1972
3       8       2       7      16  Aug 28, 1972
4      16      18      15      36  Feb 11, 1973

In [ ]:
# Split into training and testing data
from sklearn.model_selection import train_test_split

x = df[['Team 1', 'Team 2', 'Ground']]
y = df['Winner']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
df.head()

   Team 1  Team 2  Winner  Ground    Match Date
0       3       7       3     103   Jan 5, 1971
1       8       2       7     101  Aug 24, 1972
2       8       2       3      98  Aug 26, 1972
3       8       2       7      16  Aug 28, 1972
4      16      18      15      36  Feb 11, 1973

In [ ]:
# Save the prepared dataset

df.to_csv(r'/content/Prepared_match_data.csv', index= False)